In [41]:
import tkinter as tk
from tkinter import filedialog as fd
import pandas as pd
root = tk.Tk()
root.withdraw()  # hide the main window

path = fd.askopenfilename()
df=pd.read_csv(path)
#load data notebook

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22258 entries, 0 to 22257
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   property_id       22258 non-null  object
 1   address           22258 non-null  object
 2   property_type     21258 non-null  object
 3   property_subtype  0 non-null      float64
 4   bedrooms          9828 non-null   float64
 5   bathrooms         8439 non-null   float64
 6   tenure            21258 non-null  object
 7   latest_price      22258 non-null  object
 8   latest_date       22258 non-null  object
 9   new_build         22258 non-null  bool
dtypes: bool(1), float64(3), object(6)
memory usage: 1.5+ MB

In [43]:
# Check missing value per column
df.isnull().sum()

property_id             0
address                 0
property_type        1000
property_subtype    22258
bedrooms            12430
bathrooms           13819
tenure               1000
latest_price            0
latest_date             0
new_build               0
dtype: int64

In [44]:
# Check data types of all columns
df.dtypes

property_id          object
address              object
property_type        object
property_subtype    float64
bedrooms            float64
bathrooms           float64
tenure               object
latest_price         object
latest_date          object
new_build              bool
dtype: object

In [45]:
# Check for duplicate rows
df.duplicated().sum() #Result = 0 no duplicates found

np.int64(0)

In [46]:
# check columns name
df.columns.tolist()

['property_id',
 'address',
 'property_type',
 'property_subtype',
 'bedrooms',
 'bathrooms',
 'tenure',
 'latest_price',
 'latest_date',
 'new_build']

In [47]:
# Sort dataset by latest_price in descending order to identify the most expensive properties
# and inspect top 10 highest-priced listings for outlier detection and analysis
df.sort_values("latest_price", ascending=False).head(10)

,property_id,address,property_type,property_subtype,bedrooms,bathrooms,tenure,latest_price,latest_date,new_build
16111,1336276|17|,"17, Carroll Avenue, Guildford, Surrey GU1 2QJ",Detached,NaN,3.0,2.0,Freehold,"£999,999",16/12/2024,False
14591,4167046|4|,"4, Packington Square, London, Greater London N...",Flat,NaN,NaN,NaN,Leasehold,"£999,950",08/11/2024,False
19868,899278|18|,"18, Brook Road, Twickenham, Greater London TW1...",Terraced,NaN,NaN,NaN,Freehold,"£999,950",07/10/2022,False
8980,1205082|8|,"8, Linkfield Gardens, Redhill, Surrey RH1 6AF",Detached,NaN,NaN,NaN,Freehold,"£999,950",28/03/2024,False
18843,1431358|52|,"52, Coniston Road, Bromley, Greater London BR1...",Semi-detached,NaN,4.0,1.0,Freehold,"£999,950",23/06/2023,False
18669,"4288651|PROVIDENCE HOUSE, 25|FLAT 4","Providence House, 25, Flat 4, Lower Teddington...",Flat,NaN,NaN,NaN,Leasehold,"£999,950",07/01/2022,False
16641,"4514517|ARC HOUSE, 16|FLAT 129","Arc House, 16, Flat 129, Maltby Street, London...",Flat,NaN,NaN,NaN,Leasehold,"£999,000",28/01/2025,False
3111,4780620|8|FLAT 2508,"8, Flat 2508, Casson Square, London, Greater L...",Flat,NaN,NaN,NaN,Leasehold,"£998,000",26/09/2023,False
20658,"1346063|CANNING HOUSE, 7|FLAT 37","Canning House, 7, Flat 37, Heritage Walk, King...",Flat,NaN,NaN,NaN,Leasehold,"£997,850",20/06/2022,True
6460,"4357489|VALENCIA TOWER, 3|APARTMENT 127","Valencia Tower, 3, Apartment 127, Bollinder Pl...",Flat,NaN,NaN,NaN,Leasehold,"£996,450",06/04/2023,True

In [48]:
# Convert latest_date column to datetime format (YYYY-MM-DD)
df["latest_date"]=pd.to_datetime(df["latest_date"],errors="coerce",dayfirst=True)

In [49]:
# Remove £ from latest price and change type to numeric
df["latest_price"]=df["latest_price"].str.replace(r"[^\d+,]","",regex=True).str.replace(",", "", regex=False)

df["latest_price"]=pd.to_numeric(df["latest_price"],errors="coerce")

In [50]:
# Remove property_subtype column as it has no useful data (all values are missing)
df=df.drop("property_subtype",axis=1)

In [51]:
# Extract numeric property ID from combined string field
df["id"]=df["property_id"].str.split("|").str[0]
df["id"] = pd.to_numeric(df["id"], errors="coerce")

In [52]:
# Fill missing bedroom values with the average number of bedrooms
df["bedrooms"] = df["bedrooms"].fillna(df["bedrooms"].mean()).round().astype(int)

In [53]:
# Fill missing bathroom values with average and round to nearest whole number
df["bathrooms"] = df["bathrooms"].fillna(df["bathrooms"].mean()).round().astype(int)

In [54]:
#Missing categorical values were imputed using the most frequent category (mode).
df["tenure"] = df["tenure"].fillna(df["tenure"].mode()[0])

In [55]:
#Analyzed distribution of new_build values including missing entries to identify inconsistencies in categorical data.
df["new_build"].value_counts(dropna=False)

new_build
False    19800
True      2458
Name: count, dtype: int64

In [56]:
#Missing apartment values were filled using structured information extracted from the property_id field, ensuring no existing valid data was overwritten.
df["property_type"]=df["property_type"].fillna(df["property_id"].str.split("|").str[2]).str.replace(r"\d+","",regex=True).str.replace(r"\s[A-Za-z]$","",regex=True).str.title().str.strip()

In [57]:
# Standardize property types and remove invalid entries
valid_types = ["Flat", "Terraced", "Semi-Detached", "Detached"]

df["property_type"] = df["property_type"].where(df["property_type"].isin(valid_types))
df = df.dropna(subset=["property_type"])
df["property_type"].value_counts(dropna=False)

property_type
Flat             13477
Terraced          4506
Semi-Detached     2439
Detached           967
Name: count, dtype: int64

In [58]:
# Distribution of standardized property types after cleaning
df["property_type"].value_counts(dropna=False)

property_type
Flat             13477
Terraced          4506
Semi-Detached     2439
Detached           967
Name: count, dtype: int64

In [59]:
# Remove property_id column as all necessary information has already been extracted and used for feature engineering
df = df.drop(columns=["property_id"])

In [60]:
# Generate descriptive statistics (count, mean, std, min, max, quartiles)
# for numerical features to assess data distribution and identify potential outliers.
df.describe()

,bedrooms,bathrooms,latest_price,latest_date,id
count,21389.000000,21389.000000,2.138900e+04,21389,2.138900e+04
mean,2.873627,1.167376,7.262241e+05,2023-04-06 00:27:52.336247552,1.729785e+06
min,1.000000,1.000000,1.200000e+04,2015-12-10 00:00:00,8.000000e+00
25%,3.000000,1.000000,2.750000e+05,2022-08-31 00:00:00,7.075360e+05
50%,3.000000,1.000000,4.450000e+05,2023-07-11 00:00:00,1.153641e+06
75%,3.000000,1.000000,7.200000e+05,2024-04-12 00:00:00,1.752752e+06
max,18.000000,11.000000,5.612784e+07,2025-02-25 00:00:00,4.969820e+06
std,0.746208,0.494159,1.359272e+06,NaN,1.543309e+06

In [61]:
# Define outlier limits using 1st and 99th percentile
upper_limit = df["latest_price"].quantile(0.99)
lower_limit = df["latest_price"].quantile(0.01)

# Cap price values within realistic range
df["latest_price"] = df["latest_price"].clip(lower=lower_limit, upper=upper_limit)

# Keep real 6-bedroom properties
# Group only properties above 6 bedrooms into "6+"
df["bedroom_group"] = df["bedrooms"].apply( lambda x: "6+" if x > 6 else x).astype(str)

# Cap bathrooms (max realistic = 5)
df["bathrooms"] = df["bathrooms"].clip(upper=5)

In [62]:
print(df["bedroom_group"].value_counts())

bedroom_group
3     15409
2      2949
4      1317
1      1166
5       434
6        91
6+       23
Name: count, dtype: int64

In [63]:
# Move id column to the first position
df = df[["id"] + [col for col in df.columns if col != "id"]]

In [64]:
# Convert column to boolean type by standardizing values and mapping them to True/False
df["new_build"] = df["new_build"].astype(str).str.strip().str.lower().map({"true": True, "false": False})

In [65]:
# Keep original address column for reference (raw data backup)
df["address_raw"] = df["address"]

# Remove UK postcodes from the address to reduce noise and standardise text
df["address_clean"] = df["address_raw"].str.replace(
    r"\b[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}\b",
    "",
    regex=True
).str.strip()

# Extract town/city as the last meaningful segment after comma separation
df["town"] = df["address_clean"].str.split(",").str[-1].str.strip()

# Standardise inconsistent naming for Greater London
df["town"] = df["town"].replace({
    "Greater London": "London"
})

# Remove incorrectly captured street-level values (not valid towns/cities)
df = df[~df["town"].str.contains(
    "Street|Road|Avenue|Close|Drive|Lane",
    na=False
)]

# Remove known invalid or corrupted entries
df = df[df["town"] != "Abn"]

# Map UK regions/counties to representative cities for consistent city-level analysis
region_map = {
    "West Midlands": "Birmingham",
    "Greater Manchester": "Manchester",
    "Merseyside": "Liverpool",
    "Kent": "Maidstone",
    "Surrey": "Guildford",
    "East Sussex": "Brighton",
    "Buckinghamshire": "Milton Keynes",
    "Greater London": "London",
    "Brighton And Hove": "Brighton",
    "Wiltshire": "Swindon",
    "Aberdeenshire": "Aberdeen",
    "Medway": "Rochester"
}

# Apply region-to-city standardisation
df["town"] = df["town"].replace(region_map)

In [66]:
df["town"].unique()

array(['London', 'Birmingham', 'Manchester', 'Liverpool', 'Guildford',
       'Brighton', 'Maidstone', 'Aberdeen', 'Slough', 'Reading',
       'Swindon', 'Milton Keynes', 'Rochester'], dtype=object)

In [67]:
df["town"].value_counts()

town
London           11972
Guildford         1998
Maidstone         1639
Birmingham        1000
Brighton           998
Manchester         997
Liverpool          990
Swindon            699
Reading            350
Slough             291
Rochester          265
Aberdeen           103
Milton Keynes       59
Name: count, dtype: int64

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21361 entries, 0 to 22257
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21361 non-null  int64
 1   address        21361 non-null  object
 2   property_type  21361 non-null  object
 3   bedrooms       21361 non-null  int64
 4   bathrooms      21361 non-null  int64
 5   tenure         21361 non-null  object
 6   latest_price   21361 non-null  float64
 7   latest_date    21361 non-null  datetime64[ns]
 8   new_build      21361 non-null  bool
 9   bedroom_group  21361 non-null  object
 10  address_raw    21361 non-null  object
 11  address_clean  21361 non-null  object
 12  town           21361 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(1), int64(3), object(7)
memory usage: 2.1+ MB

In [69]:
df.duplicated().sum()

np.int64(0)

In [70]:
#After completing data cleaning, no missing values were found across all columns, indicating a fully structured dataset ready for analysis.
df.isnull().sum()

id               0
address          0
property_type    0
bedrooms         0
bathrooms        0
tenure           0
latest_price     0
latest_date      0
new_build        0
bedroom_group    0
address_raw      0
address_clean    0
town             0
dtype: int64

In [71]:
# Final data type check after completing all cleaning steps
df.dtypes

id                        int64
address                  object
property_type            object
bedrooms                  int64
bathrooms                 int64
tenure                   object
latest_price            float64
latest_date      datetime64[ns]
new_build                  bool
bedroom_group            object
address_raw              object
address_clean            object
town                     object
dtype: object

In [72]:
df.describe()

,id,bedrooms,bathrooms,latest_price,latest_date
count,2.136100e+04,21361.000000,21361.000000,2.136100e+04,21361
mean,1.730691e+06,2.873742,1.166472,6.776949e+05,2023-04-05 16:01:10.109077248
min,8.000000e+00,1.000000,1.000000,7.700000e+04,2015-12-10 00:00:00
25%,7.075350e+05,3.000000,1.000000,2.767500e+05,2022-08-31 00:00:00
50%,1.153661e+06,3.000000,1.000000,4.450000e+05,2023-07-11 00:00:00
75%,1.753517e+06,3.000000,1.000000,7.200000e+05,2024-04-11 00:00:00
max,4.969820e+06,18.000000,5.000000,5.703090e+06,2025-02-25 00:00:00
std,1.543799e+06,0.746417,0.482077,8.268311e+05,NaN

In [73]:
# Create connection to MySQL database (jakua) using SQLAlchemy engine
from sqlalchemy import create_engine
engine=create_engine("mysql+pymysql://root:Jakua1987#@localhost:3306/jakua")
df.to_sql(name="sale",con=engine,if_exists="replace",index=False)

21361

In [40]:
# Export cleaned dataset to Excel file for reporting and further analysis (e.g. Power BI)
df.to_excel("C:/Users/Administrator/Documents/Data/data/properties_main_cleaned.xlsx", index=False)